# Generated by Django 4.1.1 on 2022-10-01 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="amenity",
            name="description",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="room",
            name="kind",
            field=models.CharField(
                choices=[
                    ("<django.db.models.fields.CharField>", "Name"),
                    ("entire_place", "Entire Place"),
                    ("private_room", "Private Room"),
                    ("shared_room", "Shared Room"),
                ],
                max_length=200,
            ),
        ),
    ]
