# Generated by Django 4.1.1 on 2022-10-01 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0002_alter_amenity_description_alter_room_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="name",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="room",
            name="kind",
            field=models.CharField(
                choices=[
                    ("entire_place", "Entire Place"),
                    ("private_room", "Private Room"),
                    ("shared_room", "Shared Room"),
                ],
                max_length=200,
            ),
        ),
    ]
