# Generated by Django 4.1.1 on 2022-10-06 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0003_room_name_alter_room_kind"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="amenity",
            options={"verbose_name_plural": "Amenities"},
        ),
    ]
